### ISSUE TITLE
Consider minimal Java version

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-api-bp#2]
Looking at ideas for Android support like JavaMoney/javamoney-shelter#17 we should ensure, the BPs also work there. API even Java ME Embedded 8, too (which is largely compatible with Java SE 7 anyway)

**Comment by atsticks** [comment]
Current first release is building/compatible with Java SE 7. Basically with replacing the diamond operators with corresponding explicit entries should do the job rendering it compatible with Java 6.

**Comment by atsticks** [comment]
All the Objects refs must also be removed, so I propose to stick with Java 7.

**Comment by keilw** [comment]
What refs or classes do you mean?

@msgilligan already looked into Android support. As long as we don't break anything on Android (see http://stackoverflow.com/questions/7153989/java-7-language-features-with-android/13550632#13550632) Java 7 could generally work.
