### ISSUE TITLE
Package name wrong!

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-api-bp#3]
Hi,

We must not use the "javax.money" in two places even if the BP had a different Maven groupId, that's illegitimate. 
JSR 310 may have a lot of nasty mistakes (like circular dependencies, redundancies, etc.) but the BP was done properly so far in a
package org.threeten.bp;

Should do the same for the API:
Either
package org.javamoney.bp;
or
package org.javamoney.bp.api;

Depending on how the "RI Backport" should look like.
Therefore I would suggest calling it 
org.javamoney.bp.impl;
if the repository was something like "javamoney-impl-bp"
or
org.javamoney.moneta.bp;
if we go for "javamoney-moneta-bp" (or just "moneta-bp")

WDYT?

**Comment by atsticks** [comment]
Changed to 
- org.javamoney.bp.api; (API) and
- org.javamoney.bp (impl)
